version: "3.8"

services:

  server:
    build:
      context: "./back_end"
      dockerfile: Dockerfile

    ports:
      - 8080:8080

  client:
    stdin_open: true

    environment:
      - CHOKIDAR_USEPOLLING=true

    build:
      dockerfile: Dockerfile
      context: "./front_end"

    ports:
      - 4001:3000

    depends_on:
      - server
